name: Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_API_KEY: ${{ secrets.CHECKPOINT_API_KEY }}
      CHECKPOINT_CLOUD_MGMT_ID: ${{ secrets.CHECKPOINT_CLOUD_MGMT_ID }}
      CHECKPOINT_SERVER: ${{ secrets.CHECKPOINT_SERVER }}
      STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
      BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
      ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
      # STATE_FILE: ${{ secrets.STATE_FILE }}
      CHECKPOINT_SESSION_NAME: DESTROY GitHub Actions ${{ github.run_id }}
      CHECKPOINT_SESSION_DESCRIPTION: ${{ github.event_name }}  ${{ github.workflow }} - ${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      - name: Destroy rules
        run: |
          cd apps
          make down

      - name: Publish policy
        run: |
          cd apps; ../scripts/publish.sh


      - name: Destroy inventory
        run: |
          cd inventory
          make down

      - name: Publish policy
        run: |
          cd inventory; ../scripts/publish.sh
        
